#cloud-config

# apply updates using apt
package_update: true
package_upgrade: true

# Install packages
packages:
    - iptables-persistent

runcmd:
  - echo 1 > /proc/sys/net/ipv4/ip_forward
  - sed -i -e 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  - sed -i -e 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
  # Iptables Nat Rules
  - /sbin/iptables -t nat -A POSTROUTING -s '10.0.0.0/16' -o eth0 -j MASQUERADE
  - iptables-save > /etc/iptables/rules.v4

final_message:
  - "NatGateway initialisation complete."

power_state:
  delay: "+1"
  mode: reboot
  message: Bye Bye
  timeout: 30
  condition: True
